"""
00 - Seed reference and history tables (GENERATED)

Generated by infra/scripts/seed/seed_fabric.py. Do not edit by hand; re-run the
seeder to regenerate.

Reads the Parquet files uploaded to Files/seed/ and registers them as
managed Delta tables in the Lakehouse. Run this once after `azd up`, before
01_bronze_to_silver and 02_silver_to_gold.

Overwrite semantics are deliberate: reference data is a full snapshot, not an
increment. Re-running this resets the reference layer to exactly what is in
data/customdata, which is what you want when re-seeding a demo environment.
"""

SOURCE_FOLDER = "Files/seed"

TABLES = ['bronze_alarms', 'bronze_connectivity', 'bronze_dma_flow', 'bronze_dma_pressure', 'bronze_energy', 'bronze_telemetry', 'bronze_water_quality', 'ref_assets', 'ref_calibrations', 'ref_crew_availability', 'ref_deployments', 'ref_devices', 'ref_failure_modes', 'ref_module_twins', 'ref_nrw_monthly', 'ref_regulatory_limits', 'ref_sites', 'ref_spare_parts', 'ref_workorders']

for table_name in TABLES:
    path = f"{SOURCE_FOLDER}/{table_name}.parquet"
    try:
        df = spark.read.parquet(path)
    except Exception as exc:  # noqa: BLE001
        print(f"SKIP  {table_name}: {exc}")
        continue

    (df.write
       .format("delta")
       .mode("overwrite")
       .option("overwriteSchema", "true")
       .saveAsTable(table_name))
    print(f"OK    {table_name}: {df.count()} rows")

print("\nReference seed complete. Next: 01_bronze_to_silver.")
